-- MySQL Script generated by MySQL Workbench
-- Sat Jul 27 18:34:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema forum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema forum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `forum` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `forum` ;

-- -----------------------------------------------------
-- Table `forum`.`t_badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`t_badge` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `img_location` VARCHAR(45) NOT NULL,
  `date_created` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `forum`.`t_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`t_user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `activated` TINYINT(1) NOT NULL DEFAULT '1',
  `date_created` DATETIME NOT NULL,
  `avatar_location` VARCHAR(255) NULL DEFAULT 'avatar/default_avatar.png',
  `bio` VARCHAR(255) NULL DEFAULT NULL,
  `roles` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `forum`.`t_badge_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`t_badge_user` (
  `id` INT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `badge_id` INT NOT NULL,
  `is_valid` TINYINT NOT NULL DEFAULT '1',
  `expired_date` DATETIME NULL DEFAULT NULL,
  `remark` VARCHAR(45) NULL DEFAULT NULL,
  `date_created` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_t_badge_user_t_badge1_idx` (`badge_id` ASC) VISIBLE,
  INDEX `fk_t_badge_user_t_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_badge_user_t_badge1`
    FOREIGN KEY (`badge_id`)
    REFERENCES `forum`.`t_badge` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_badge_user_t_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `forum`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `forum`.`t_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`t_category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `weight` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `display_name` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `forum`.`t_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`t_post` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `body` TEXT NULL DEFAULT NULL,
  `date_created` DATETIME NOT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  `category_id` BIGINT NULL DEFAULT NULL,
  `comment_count` INT NULL DEFAULT '0',
  `hit_count` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `category_id` (`category_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `t_post_ibfk_1`
    FOREIGN KEY (`category_id`)
    REFERENCES `forum`.`t_category` (`id`),
  CONSTRAINT `t_post_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `forum`.`t_user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 60
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `forum`.`t_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`t_comment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `body` TEXT NOT NULL,
  `post_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `post_id` (`post_id` ASC) VISIBLE,
  CONSTRAINT `t_comment_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `forum`.`t_user` (`id`),
  CONSTRAINT `t_comment_ibfk_2`
    FOREIGN KEY (`post_id`)
    REFERENCES `forum`.`t_post` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `forum`.`t_verification_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum`.`t_verification_token` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `token` TEXT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `expiry_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `t_verification_token_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `forum`.`t_user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
